#!/bin/bash

set -e

growpart /dev/vda 1
resize2fs /dev/vda1

# Update packages
apt update --yes

# Install ssh early
apt install --yes ssh
perl -pi -e 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart ssh

# Install tools
apt install --yes plocate

# Install ansible
apt install --yes software-properties-common
add-apt-repository --yes --update ppa:ansible/ansible
apt install --yes ansible ansible-core python3-pip
python3 -m pip install ansible-navigator

# Install system users
addgroup --gid 500 ansible
adduser --system --uid 500 --gid 500 --home /var/lib/ansible --shell /bin/bash --gecos "Ansible User" ansible