#!/bin/bash

growpart /dev/vda 1
resize2fs /dev/vda1

# Update packages
apt update --yes

# Install ssh early
apt install --yes ssh
perl -pi -e 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart ssh

# Install tools
apt install --yes plocate

touch /usr/local/sbin/first-boot-script.done
chmod -x /usr/local/sbin/first-boot-script