#!/bin/bash

growpart /dev/vda 1
resize2fs /dev/vda1

# Update packages
apt update --yes

# Install ssh early
apt install --yes openssh-server
# Workaround Ubuntu 26.04 ssh server not starting
rm -f /etc/ssh/ssh_host_*
ssh-keygen -A

perl -pi -e 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl enable ssh
systemctl start ssh

# Install tools
apt install --yes \
  net-tools \
  plocate \
  strace \
  tcpdump

touch /usr/local/sbin/first-boot-script.done
chmod -x /usr/local/sbin/first-boot-script