---
# handlers file for kube-container-runtime
- name: Restart - crio
  service:
    name: crio
    state: restarted
  
- name: Restart - containerd
  service:
    name: containerd
    state: restarted