---
# tasks file for kube-lb

- name: Deb Install - keepalived
  apt:
    name:
      - keepalived
    state: latest

- name: keepalived ipvs config - keepalived.conf
  template:
    src: "{{role_path}}/templates/etc/keepalived/keepalived.conf.j2"
    dest: /etc/keepalived/keepalived.conf
  notify: Restart - keepalived

- name: Service - keepalived
  service:
    name: keepalived
    state: started
