---
# handlers file for kube-common
- name: Restart - kubelet
  service:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: Restart - docker
  service:
    name: docker
    state: restarted

- name: Restart - crio
  service:
    name: crio
    state: restarted
  
- name: Restart - containerd
  service:
    name: docker
    state: restarted