---
# handlers file for kube-common
- name: Restart - containerd
  service:
    name: containerd
    state: restarted

- name: Restart - systemd-sysctl
  service:
    name: systemd-sysctl
    state: restarted
