---
- name: Install - debootstrap
  apt:
    name: debootstrap
    state: latest

- name: Install - schroot
  apt:
    name: schroot
    state: latest

- name: Install - libvirt
  apt:
    name: libvirt-clients
    state: latest

- name: Install - libvirt python3
  apt:
    name: python3-libvirt
    state: latest

- name: Install - QEMU KVM
  apt:
    name: qemu-system-x86
    state: latest
  
- name: VM Image - create qcow2 images
  shell:
    cmd: qemu-img create -f qcow2 /var/lib/libvirt/images/{{item}}.qcow2 20G
    creates: /var/lib/libvirt/images/{{item}}.qcow2
  loop:
    - kube-lab01
    - kube-lab02
    - kube-lab03

- name: VM Image - partition qcow2 images
  shell:
    cmd: 



