---
# tasks file for kube-net
- name: Untaint master mode - kubectl taint nodes ...
  shell:
    cmd: bash -c 'kubectl taint nodes kubemaster1 node-role.kubernetes.io/master-; touch {{ touchD }}/untaint'
    creates: "{{ touchD }}/untaint"

- name: Calico template
  template:
    src: "{{role_path}}/templates/calico.yaml.j2"
    dest: "{{ filesD }}/calico.yaml"
    owner: bin
    group: wheel
    mode: '0644'

- name: Install Calico
  shell: 
    cmd: kubectl apply -f {{ filesD }}/calico.yaml && touch {{ touchD }}/pod_calico
    creates: "{{ touchD }}/install_calico"

- name: Namespace kubevirt
  shell:
    cmd: kubectl create namespace kubevirt; touch {{ touchD }}/namespace_kubevirt
    creates: "{{ touchD }}/namespace_kubevirt"
