---
# tasks file for kube-net
- name: Install Weave
  shell: 
    cmd: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" && touch "{{ touchD }}/install_weave"
    creates: "{{ touchD }}/install_weave"