---
- name: Wait For - kubeadm install on seed host
  wait_for:
    path: /usr/bin/kubeadm
  delegate_to: "{{ seedmaster }}"

- name: Wait For - kubeadm install
  wait_for:
    path: /usr/bin/kubeadm
    state: started
    timeout: 300

- name: Wait For - containerd start
  wait_for:
    path: /run/containerd/containerd.sock
    state: present
    timeout: 300

# tasks file for kube-control-plane
- name: Initialization - kubeadm init seedmaster
  shell:
    cmd: kubeadm init --patches {{filesD}}/kubeadm-init-patches --apiserver-bind-port {{ kube_apiserver_port }} --control-plane-endpoint "{{ kube_apiserver_vip_hostname }}:{{ kube_apiserver_vip_port }}" --upload-certs --pod-network-cidr={{ pod_network_cidr }} > /root/kubeadmin_init.log
    creates: "/etc/kubernetes/admin.conf"
  when: inventory_hostname == seedmaster

- name: Wait - kubeadmin init seedmaster
  wait_for:
    path: "/etc/kubernetes/admin.conf"
  delegate_to: "{{ seedmaster }}"

- name: Install - kube-gen-add-control.sh
  copy:
    src: "{{role_path}}/files/usr/local/sbin/kube-gen-add-control.sh"
    dest: "/usr/local/sbin/kube-gen-add-control.sh"
    mode: "700"
  when: inventory_hostname == seedmaster

- name: Generate - kube-add-control.sh
  shell:
    cmd: bash -c "umask 077; bash /usr/local/sbin/kube-gen-add-control.sh /var/local/ansible/files/kube-add-control.sh"
    creates: "/var/local/ansible/files/kube-add-control.sh"
  when: inventory_hostname == seedmaster

- name: Wait - kube-add-control.sh
  wait_for:
    path: /var/local/ansible/files/kube-add-control.sh
  delegate_to: "{{ seedmaster }}"
  when: inventory_hostname != seedmaster

- name: Fetch - kube-add-control.sh
  fetch:
    src: "/var/local/ansible/files/kube-add-control.sh"
    dest: /tmp/
    flat: true
  delegate_to: "{{ seedmaster }}"
  when: inventory_hostname != seedmaster

- name: Copy - kube-add-control.sh
  copy:
    src: /tmp/kube-add-control.sh
    dest: /usr/local/sbin/kube-add-control.sh
    mode: "700"
  when: inventory_hostname != seedmaster

- name: Wait - kubeadmin init seedmaster port
  wait_for:
    host: 0.0.0.0
    port: 6443
    timeout: 1800
  delegate_to: "{{ seedmaster }}"
  when: inventory_hostname != seedmaster

- name: Wait for kube-net
  wait_for:
    path: "{{ touchD }}/install_calico"
  delegate_to: "{{ seedmaster }}"
  when: inventory_hostname != seedmaster

- name: Check if kubernetes has been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kube_config_file

- name: Disable backend vip temporarily
  shell:
    cmd: backendvip.py disable --all-vips
  when:
    - not kube_config_file.stat.exists
    - inventory_hostname != seedmaster

- name: Kubernetes add control
  shell:
    cmd: /usr/local/sbin/kube-add-control.sh
    creates: /etc/kubernetes/admin.conf
  when: inventory_hostname != seedmaster
  notify: Enable backend vip

- name: Config - kubectl (1/2)
  file:
    path: /root/.kube
    state: directory
    mode: "750"

- name: Config - kubectl (2/2)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: "600"
    remote_src: yes

- name: Wait for kubernetes join to complete
  shell:
    cmd: "kubectl wait --for=condition=Ready node/{{inventory_hostname}} --timeout=300s"
  delegate_to: "{{ seedmaster }}"
  when: inventory_hostname != seedmaster

- name: Check if csrs are pending
  shell:
    cmd: "kubectl get csr | grep Pending | grep kubernetes.io"
  register: csrs_pending
  changed_when: false
  failed_when: false

- name: Sign pending CSRs
  shell:
    cmd: "kubectl get csr | grep Pending | grep kubernetes.io | awk '{print $1}' | xargs -I {} kubectl certificate approve {}"
  when: csrs_pending.stdout != ""

# Match the version of etcd using
# kubectl get pods -n kube-system -l component=etcd -o jsonpath='{.items[*].spec.containers[*].image}'

- name: Download etcdctl etcdutl
  get_url:
    url: https://storage.googleapis.com/etcd/v3.6.8/etcd-v3.6.8-linux-amd64.tar.gz
    dest: "{{filesD}}/etcd-v3.6.8-linux-amd64.tar.gz"

- name: Extract etcdctl etcdutl
  unarchive:
    src: "{{filesD}}/etcd-v3.6.8-linux-amd64.tar.gz"
    dest: "{{filesD}}/"
    creates: "{{filesD}}/etcd-v3.6.8-linux-amd64/etcdctl"
    remote_src: yes

- name: Install etcdctl etcdutl
  copy:
    src: "{{filesD}}/etcd-v3.6.8-linux-amd64/{{item}}"
    dest: "/usr/local/sbin/{{item}}"
    owner: "root"
    group: "root"
    mode: "0750"
    remote_src: yes
  loop:
    - etcdctl
    - etcdutl

- name: Install etcdbackup
  copy:
    src: "{{role_path}}/files/usr/local/sbin/etcdbackup.py"
    dest: "/usr/local/sbin/etcdbackup"
    owner: "root"
    group: "root"
    mode: "0750"

- name: Cron etcdbackup
  cron:
    name: etcdbackup
    minute: "0"
    hour: "0"
    job: /usr/local/sbin/etcdbackup backup

- name: Create metrics-server directory
  file:
    path: "{{filesD}}/{{item}}"
    state: directory
  loop:
    - "metrics-server"
    - "metrics-server/v0.9.0"

- name: Install metrics-server files
  copy:
    src: "{{role_path}}/files/metrics-server/{{item}}"
    dest: "{{filesD}}/metrics-server/{{item}}"
  loop:
    - v0.9.0/components.yaml
    - v0.9.0/components-custom.yaml
    - metrics-server-csr.conf

- name: Check age of /etc/kubernetes/admin.conf
  stat:
    path: "/etc/kubernetes/admin.conf"
  register: stat_kube_config_file

- name: Check age of metrics-server tls key
  stat:
    path: "{{filesD}}/metrics-server/tls.crt"
  register: stat_metrics_server_tls_crt

- block:
    - name: Create metrics-server key
      shell:
        cmd: "umask 0077 && openssl genrsa -out {{filesD}}/metrics-server/tls.key 2048"

    - name: Create metrics-server csr
      shell:
        cmd: "umask 0077 && openssl req -new -key {{filesD}}/metrics-server/tls.key -out {{filesD}}/metrics-server/tls.csr -config {{filesD}}/metrics-server/metrics-server-csr.conf"

    - name: Sign metrics-server crt
      shell:
        cmd: "umask 0077 && openssl x509 -req -in {{filesD}}/metrics-server/tls.csr -CA /etc/kubernetes/pki/ca.crt -CAkey /etc/kubernetes/pki/ca.key -CAcreateserial -out {{filesD}}/metrics-server/tls.crt -days 365 -extensions v3_ext -extfile {{filesD}}/metrics-server/metrics-server-csr.conf"

    - name: Add metrics-server secret to kubernetes
      shell:
        cmd: "kubectl create secret tls metrics-server-tls -n kube-system --cert={{filesD}}/metrics-server/tls.crt --key={{filesD}}/metrics-server/tls.key -n kube-system"

    - name: Remove tls key, csr
      file:
        path: "{{filesD}}/metrics-server/{{item}}"
        state: absent
      loop:
        - tls.key
        - tls.csr
  when: inventory_hostname == seedmaster and (not stat_metrics_server_tls_crt.stat.exists or stat_metrics_server_tls_crt.stat.mtime < stat_kube_config_file.stat.mtime)

- name: Install metric-servers server
  shell:
    cmd: "kubectl apply -f {{filesD}}/metrics-server/v0.9.0/components.yaml && touch {{touchD}}/install_metrics_server"
    creates: "{{ touchD }}/install_metrics_server"
  when: inventory_hostname == seedmaster
