---
- name: Wait For - kubeadm install on seed host
  wait_for:
    path: /usr/bin/kubeadm
  delegate_to: "{{ seedmaster }}"

- name: Wait For - kubeadm install
  wait_for:
    path: /usr/bin/kubeadm

# tasks file for kube-control-plane
- name: Initialization - kubeaadm init seedmaster
  shell:
    cmd: kubeadm init --control-plane-endpoint "{{ kube_apiserver_vip_hostname }}:{{ kube_apiserver_frontend_port }}" --upload-certs --pod-network-cidr={{ pod_network_cidr }} > /root/kubeadmin_init.log
    creates: "/etc/kubernetes/admin.conf"
  when: inventory_hostname == seedmaster 

- name: Wait - kubeadmin init seedmaster
  wait_for:
    path: "/etc/kubernetes/admin.conf"
  delegate_to: "{{ seedmaster }}"

- name: Install - kube-gen-add-control.sh
  copy:
    src: "{{role_path}}/files/usr/local/sbin/kube-gen-add-control.sh"
    dest: "/usr/local/sbin/kube-gen-add-control.sh"
    mode: '700'
  when: inventory_hostname == seedmaster 

- name: Generate - kube-add-control.sh
  shell:
    cmd: /usr/local/sbin/kube-gen-add-control.sh > /var/local/ansible/files/kube-add-control.sh; at now + 2hour <<< 'rm -f /var/local/ansible/files/kube-add-control.sh'
    creates: /var/local/ansible/files/kube-add-control.sh
  when: inventory_hostname == seedmaster 

- name: Wait - kube-add-control.sh
  wait_for:
    path: /var/local/ansible/files/kube-add-control.sh
  delegate_to: "{{ seedmaster }}"

- name: Fetch - kube-add-control.sh
  fetch:
    src: /var/local/ansible/files/kube-add-control.sh
    dest: /tmp/
    flat: true
  when: inventory_hostname == seedmaster 

- name: Wait - kube-add-control.sh
  wait_for:
    path: /tmp/kube-add-control.sh
  delegate_to: localhost

- name: Copy - kube-add-control.sh
  copy:
    src: /tmp/kube-add-control.sh
    dest: /usr/local/sbin/kube-add-control.sh
    mode: '700'
  when: inventory_hostname != seedmaster 

- name: Wait - kubeadmin init seedmaster port
  wait_for:
    host: 0.0.0.0
    port: 6443
  delegate_to: "{{ seedmaster }}"

- name: Initialization - kubeadm init
  shell:
    cmd: /usr/local/sbin/kube-add-control.sh
    creates: /etc/kubernetes/admin.conf

- name: Config - kubectl (1/2)
  file:
    path: /root/.kube
    state: directory
    mode: '750'

- name: Config - kubectl (2/2)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: '600'
    remote_src: yes