---
# tasks file for kube-control-plane
- name: Initialisation - kubeadmin init
  shell:
    cmd: kubeadm init --pod-network-cidr={{ pod_network_cidr }} > /root/kubeadmin_init.log && touch /var/local/ansible/touch/kubeadm-init
    creates: /var/local/ansible/touch/kubeadm-init

- name: Config - kubectl (1/2)
  file:
    path: /root/.kube
    state: directory
    mode: '750'

- name: Config - kubectl (2/2)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes