---
# tasks file for kube-common

#
# Kernel modules
#
- name: Kernel modules - overlay br_netfilter
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/kubernetes.conf

- name: Run - modprobe
  shell:
    cmd: "modprobe {{ item }} && touch /var/local/ansible/touch/modprobe-{{ item }}"
    creates: "/var/local/ansible/touch/modprobe-{{ item }}"
  loop:
    - br_netfilter
    - overlay

#
# sysctl.conf(s)
#
- sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
    state: present
    reload: yes
  loop:
    - { key: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { key: net.bridge.bridge-nf-call-ip6tables, value: 1 }
    - { key: net.ipv4.ip_forward, value: 1 }

#
# RPM Installations
#
- name: RPM Install - all
  dnf:
    name:
      - lvm2
      - device-mapper-persistent-data
      - fuse-overlayfs
      - libcgroup
      - libcgroup-tools
      - container-selinux
      - cri-o
    state: latest

- name: RPM Install - kubelet kubeadm kubectl
  dnf:
    name: ['kubelet', 'kubeadm', 'kubectl']
    disable_excludes: kubernetes
    state: present

#
# System configuration  
#
# Kubernetes CGroups doesn't handle swap well.
# https://github.com/kubernetes/kubernetes/issues/53533
- name: Config - /etc/fstab disable swap 
  shell:
    cmd: "perl -pi -e 's/^([^#]+\\sswap\\s+swap.*)/# $1/' /etc/fstab && touch /var/local/ansible/touch/swapoff-fstab"
    creates: /var/local/ansible/touch/swapoff-fstab

- name: Config - disable swap
  shell:
    cmd: swapoff -a && touch /var/local/ansible/touch/swapoff
    creates: /var/local/ansible/touch/swapoff

- name: Config - SELinux permissive
  ansible.posix.selinux:
    configfile: /etc/selinux/config
    policy: targeted
    state: permissive

#
# Configuration
#
- name: Config - /etc/sysconfig/kubelet
  copy:
    content: |
      KUBELET_EXTRA_ARGS=--feature-gates="AllAlpha=false,RunAsGroup=true" --container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --runtime-request-timeout=5m
    dest: /etc/sysconfig/kubelet

#
# Services
#
- name: Service - firewalld (disabled)
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: Service - crio
  service:
    name: crio
    enabled: yes
    state: started
    daemon_reload: yes

- name: Service - kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
    daemon_reload: yes