#!/usr/bin/env python3

# The config file is libvirt/manifest/kubenet.yml

"""
Ansible setup.

Usage:
    ansiblesetup.py inventory -c=<config> <new_inventory_file>

Options:
    -h --help             Show this screen.
    -c --config=<config>  Path to YAML configuration file.
    -O --overwrite        Overwrite the existing inventory file.
    <new_inventory_file>  Path to new inventory file to be generated.
"""

import random
import string
import os
import yaml

from docopt import docopt
from pathlib import Path

#
# Config loading
#
    
def load_yaml_config(config_path: Path) -> dict:
    with open(config_path, "r") as f:
        return yaml.safe_load(f)

def generate_inventory(config: dict) -> str:
    inventory_lines = []
    inventory_lines.append("# Generated by ansiblesetup.py. DO NOT EDIT")
    groups = {}
    for host in config.get("hosts", []):
        fqdn = host["fqdn"]
        group = host["ansible"]["group"]
        ansible_conf = host.get("ansible", {})
        if "vars" in ansible_conf:
            vars_lines = [f"{key}={value}" for key, value in ansible_conf["vars"].items()]
            groups.setdefault(group, []).append(f"{fqdn} {' '.join(vars_lines)}")
        else:
            groups.setdefault(group, []).append(fqdn)
    
    all_vars = {}
    for key, value in config.get("ansible", {}).get("inventory", {}).get("all_vars", {}).items():
        all_vars[key] = value
    
    lb_vars = {}
    for key, value in config.get("ansible", {}).get("inventory", {}).get("lb_vars", {}).items():
        lb_vars[key] = value
    
    for gen_lb_vars in config.get("ansible", {}).get("inventory", {}).get("gen_lb_vars", []):
        if gen_lb_vars == "keepalived_auth_pass":
            keepalive_password_file = Path("tmp/keepalived_auth_pass.txt")
            keepalive_password = generate_keepalived_password(keepalive_password_file)
            lb_vars["keepalived_auth_pass"] = f"'{keepalive_password}'"
    
    inventory_lines.append(f"[all:vars]")
    for all_var_key, all_var_value in all_vars.items():
        inventory_lines.append(f"{all_var_key}={all_var_value}")
    inventory_lines.append("")  # Add a blank line after all:vars
    
    inventory_lines.append(f"[lb:vars]")
    for lb_var_key, lb_var_value in lb_vars.items():
        inventory_lines.append(f"{lb_var_key}={lb_var_value}")
    inventory_lines.append("")  # Add a blank line after lb:vars

    for group, hosts in groups.items():
        inventory_lines.append(f"[{group}]")
        inventory_lines.extend(hosts)
        inventory_lines.append("")  # Add a blank line after each group
    return "\n".join(inventory_lines)

def generate_password(length: int = 12) -> str:
    characters = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(characters) for _ in range(length))

def generate_keepalived_password_file(password: str, file_path: Path) -> str:
    if file_path.exists():
        with open(file_path, "r") as f:
            return f.read().strip()

    # Ensure the parent directory exists
    file_path.parent.mkdir(parents=True, exist_ok=True)
    # Write the password to the file with permissions 600
    with open(file_path, "w") as f:
        f.write(password)
    os.chmod(file_path, 0o600)

def generate_keepalived_password(file_path: Path) -> str:
        return generate_keepalived_password_file(generate_password(), file_path)

#
# Main
#

def main():
    args = docopt(__doc__)
    config = load_yaml_config(Path(args["--config"]))
    new_inventory_file = Path(args["<new_inventory_file>"])

    # Generate inventory content based on the config
    inventory_content = generate_inventory(config)

    # Write the inventory content to the new file
    with open(new_inventory_file, "w") as f:
        f.write(inventory_content)
    os.chmod(new_inventory_file, 0o600)


if __name__ == "__main__":
    main()