---
# tasks file for soe
- name: Wait for first-boot-script
  wait_for:
    path: /usr/local/sbin/first-boot-script.done
    state: present

#
# All Users here
#
- name: User - root (disable password)
  user:
    name: root
    password: "*"

- name: User - kubectl
  user:
    name: kubectl
    uid: 800
    system: True

#
# Deb Installations
#
- name: Apt Install - iproute2 python3-backoff python3-docopt
  apt:
    name:
      - at
      - iproute2
      - python3-backoff
      - python3-docopt
    state: latest

- name: Atd daemon
  service:
    name: atd
    state: started

#
# System configuration
#
- name: Sysctl - vm.swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "1"

- name: Hostname - system hostname
  hostname:
    name: "{{ inventory_hostname }}"

  # Ansible generated files. Doesn't really belong here but SOE should be everywhere
- name: Ansible generated - Location for Ansible generated files
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/local/ansible
    - /var/local/ansible/touch
    - /var/local/ansible/files
