---
# tasks file for soe

#
# Repositories
#
- name: Repository - CRI-O 
  get_url:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.19/CentOS_7/devel:kubic:libcontainers:stable:cri-o:1.19.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.19.repo
    mode: 644

- name: Repository - Kubernetes
  copy:
    src: "{{ role_path }}/files/etc/yum.repos.d/kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo

#
# All Users here
#
- name: User - root (disable password)
  user:
    name: root
    password: '*'

- name: User - kubectl
  user:
    name: kubectl
    uid: 800
    system: True

#
# RPM Installations
#
- name: RPM Install - nscd
  dnf:
    name: nscd
    state: latest

#
# System configuration
#
- name: Sysctl - vm.swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '1'

- name: Hostname - system hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Config - /etc/nscd.conf
  copy:
    src: "{{role_path}}/files/etc/nscd.conf"
    dest: /etc/nscd.conf
  notify: Restart - nscd

- name: Config - /etc/nsswitch.conf
  copy:
    src: "{{role_path}}/files/etc/nscd.conf"
    dest: /etc/nsswitch.conf
  
  # Ansible generated files. Doesn't really belong here but SOE should be everywhere
- name: Ansible generated - Location for Ansible generated files 
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/local/ansible
    - /var/local/ansible/touch
    - /var/local/ansible/files