---
# tasks file for soe

#
# Repositories
#
- name: Repository - Kubernetes
  copy:
    src: "{{ role_path }}/files/etc/yum.repos.d/kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Docker CE
  shell:
    cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  args:
    warn: false

#
# All Users here
#
- name: User - root (disable password)
  user:
    name: root
    password: '*'

- name: User - kubectl
  user:
    name: kubectl
    uid: 800
    system: True

#
# RPM Installations
#
- name: RPM Install - nscd python39 tc
  dnf:
    name:
      - nscd
      - python39
      - tc
    state: latest

#
# Pip3
#
- name: Pip3 Install - backoff docopts
  pip:
    name:
      - backoff
      - docopts
    executable: pip3
    state: latest

#
# Security
#

- name: Config - SELinux permissive
  ansible.posix.selinux:
    configfile: /etc/selinux/config
    policy: targeted
    state: permissive

- name: Service - firewalld (disabled)
  service:
    name: firewalld
    enabled: no
    state: stopped

#
# System configuration
#
- name: Sysctl - vm.swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '1'

- name: Hostname - system hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Config - /etc/nscd.conf
  copy:
    src: "{{role_path}}/files/etc/nscd.conf"
    dest: /etc/nscd.conf
  notify: Restart - nscd

- name: Config - /etc/nsswitch.conf
  copy:
    src: "{{role_path}}/files/etc/nscd.conf"
    dest: /etc/nsswitch.conf
  
  # Ansible generated files. Doesn't really belong here but SOE should be everywhere
- name: Ansible generated - Location for Ansible generated files 
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/local/ansible
    - /var/local/ansible/touch
    - /var/local/ansible/files