- hosts: all
  roles:
    - soe

    - role: kube-common
      when: "'kubecluster' in group_names"

    - role: kube-control-plane
      when: "'kubemaster' in group_names"

    - role: kube-container-runtime
      when: "'kuberun' in group_names"

    - role: kube-net
      when: "'kubemaster' in group_names"

    - role: kube-mgmt
      when: "'kubemaster' in group_names"
    
    - role: kube-dashboard
      when: "'kubemaster' in group_names"

    - role: kube-ingress-controller
      when: "'kubemaster' in group_names"
    
    - role: load-balancer
      when: "'kubelb' in group_names"