- hosts: all
  roles:
    - soe

    - role: load-balancer-backend
      when: "'control' in group_names"

    - role: load-balancer
      when: "'lb' in group_names"

    - role: kube-common
      when: "'control' in group_names"

    - role: kube-common
      when: "'worker' in group_names"

    - role: kube-control-plane
      when: "'control' in group_names"

    - role: kube-net
      when: "'control' in group_names"

    - role: kube-mgmt
      when: "'control' in group_names"

    - role: kube-container-runtime
      when: "'worker' in group_names"
