---
# tasks file for kube-kubectl

#
# RPM Installations
#
- name: RPM Install - all
  dnf:
    name:
      - kubectl

- name: Kubernetes - Wait for Admin Init
  wait_for:
    path: /var/local/ansible/touch/kubeadm-init
    timeout: 1200
  delegate_to: "{{ groups['kubemaster'][0] }}"
 
- name: kubectl - get /etc/kubernetes/admin.conf
  shell:
    cmd: cat /etc/kubernetes/admin.conf
  register: kubeadmconf
  delegate_to: "{{ groups['kubemaster'][0] }}"

- set_fact:
    kubeadmconf: "{{ kubeadmconf.stdout }} "

- name: kubectl - mkdir /home/kubectl/.kube
  file:
    path: /home/kubectl/.kube
    state: directory
    owner: kubectl
    group: kubectl
    mode: 0750

- name: kubectl - set /home/kubectl/.kube/config
  copy:
    content: "{{ kubeadmconf }}"
    dest: /home/kubectl/.kube/config
    owner: kubectl
    mode: 0600