---
# tasks file for kube-container-runtime

#
# Kubernetes join
#
- name: Kubernetes - Wait for Admin Init
  wait_for:
    path: /var/local/ansible/touch/kubeadm-init
  delegate_to: "{{ groups['kubemaster'][0] }}"

- name: Kubernetes - Join token
  shell:
    cmd: "kubeadm token create --print-join-command && touch /var/local/ansible/touch/kubeadm-joined-{{ inventory_hostname_short }}"
    creates: "/var/local/ansible/touch/kubeadm-joined-{{ inventory_hostname_short }}"
  register: kubeadmjoincmd
  delegate_to: "{{ groups['kubemaster'][0] }}"

- set_fact:
    kubeadmjoin: "{{ kubeadmjoincmd.stdout }} "

- name: Kubernetes - Join Command
  shell:
    cmd: "{{ kubeadmjoin }} && touch /var/local/ansible/touch/kubeadm-join"
    creates: /var/local/ansible/touch/kubeadm-join