---
# tasks file for kube-container-runtime

#
# Kubernetes join
#
- name: Kubernetes - Wait for Admin Init
  wait_for:
    path: /etc/kubernetes/admin.conf
  delegate_to: "{{ seedmaster }}"

- name: Check if already joined
  stat:
    path: /var/local/ansible/touch/kubeadm-join
  register: has_joined

- block:
    - name: Wait - kubeadmin init seedmaster port
      wait_for:
        host: 127.0.0.1
        port: 6443
      delegate_to: "{{ seedmaster }}"

    - name: Kubernetes - Join token
      shell:
        cmd: "kubeadm token create --print-join-command"
      register: kubeadmjoincmd
      delegate_to: "{{ seedmaster }}"

    - set_fact:
        kubeadmjoin: "{{ kubeadmjoincmd.stdout }} --patches {{filesD}}/kubeadm-init-patches"

    - name: Kubernetes - Join Command
      shell:
        cmd: "{{ kubeadmjoin }} && touch /var/local/ansible/touch/kubeadm-join"

    - name: Wait for kubernetes join to complete
      shell:
        cmd: "kubectl wait --for=condition=Ready node/{{inventory_hostname}} --timeout=300s"
      delegate_to: "{{ seedmaster }}"

    - name: Sign csrs
      shell:
        cmd: "kubectl get csr | grep Pending | grep kubernetes.io | awk '{print $1}' | xargs -I {} kubectl certificate approve {}"
      delegate_to: "{{ seedmaster }}"

    - name: Restart - kubelet
      service:
        name: kubelet
        state: restarted

  when: not has_joined.stat.exists
