---
# tasks file for kube-container-runtime

#
# Kubernetes join
#
- name: Kubernetes - Wait for Admin Init
  wait_for:
    path: /etc/kubernetes/admin.conf
  delegate_to: "{{ seedmaster }}"

- name: Check if already joined
  stat:
    path: /var/local/ansible/touch/kubeadm-join
  register: has_joined

- block:
    - name: Wait - kubeadmin init seedmaster port
      wait_for:
        host: 127.0.0.1
        port: 6443
      delegate_to: "{{ seedmaster }}"

    - name: Kubernetes - Join token
      shell:
        cmd: "kubeadm token create --print-join-command"
      register: kubeadmjoincmd
      delegate_to: "{{ seedmaster }}"

    - set_fact:
        kubeadmjoin: "{{ kubeadmjoincmd.stdout }} "

    - name: Kubernetes - Join Command
      shell:
        cmd: "{{ kubeadmjoin }} && touch /var/local/ansible/touch/kubeadm-join"
  when: not has_joined.stat.exists
